### ISSUE TITLE
Calling stopVideo in dispose() function throws an error

### ISSUE THREAD

**Issue by 2Pacalypse-** [videojs/videojs-youtube#410]
This error is only happening in the latest version, introduced with  this commit: https://github.com/videojs/videojs-youtube/commit/8ee1bb16d6d1c8aedc875d306c1e884fa90349e1

The error message is `Cannot call function postMessage on property null`. Which means `contentWindow` property in the youtube player is `null`.

I'm not entirely sure why this happens, but if anyone has any ideas on how to fix it, it would be helpful.

**Comment by clark-stevenson** [comment]
I can confirm the same thing here.  I runtime on `this.ytPlayer.stopVideo();` within that commit.

**Comment by gkatsev** [comment]
I cannot reproduce this locally. Do you have a [reduced test case](https://css-tricks.com/reduced-test-cases/)? It would make it a lot easier for us to reproduce the issue you are experiencing and thus fixing it.

**Comment by clark-stevenson** [comment]
In the latest version, I no long receive that error. 

It has since been replaced with the following for me:

```
www-widgetapi.js:121 Uncaught TypeError: Cannot read property 'postMessage' of null
    at X.g.C (https://s.ytimg.com/yts/jsbin/www-widgetapi-vfl3Qaxnn/www-widgetapi.js:121:351)
    at V (https://s.ytimg.com/yts/jsbin/www-widgetapi-vfl3Qaxnn/www-widgetapi.js:113:99)
    at X.(anonymous function).getCurrentTime.Rb.(anonymous function) [as stopVideo] (https://s.ytimg.com/yts/jsbin/www-widgetapi-vfl3Qaxnn/www-widgetapi.js:136:124)
    at constructor.dispose (http://192.168.1.70:2200/lib/videojs-youtube/Youtube.js:66:23)
    at Player.dispose (http://192.168.1.70:2200/lib/videojs/video.js:9389:161)
    at VideoElementView.destroy (http://192.168.1.70:2200/js/release.js:5139:37)
    at EndScreenView.ScreenView.destroyVideo (http://192.168.1.70:2200/js/release.js:5684:36)
    at EndScreenView.ScreenView.destroy (http://192.168.1.70:2200/js/release.js:5887:26)
```

I will try to get a reduced test case, but won't likely be until the start of the year.

**Comment by RTKWAK** [comment]
Hello, 
I've exactly the same error message. I use the _videojs-youtube v2.2.0._
And after i cannot open again this video, i have this message :
`video.js:22914 VIDEOJS: WARN: Player "modal-modalYoutube-XX" is already initialised. Options will not be applied.`

I tried with the v2.1.1 but i have a another error message ...

What is the solution ? What old version use ?

**Comment by gkatsev** [comment]
I cannot reproduce any of these errors. Going to close for now but I can re-open if we get a reduced test case.
