### ISSUE TITLE
Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.

### ISSUE THREAD

**Issue by misaizdaleka** [videojs/videojs-youtube#416]
Hi, 

I'm getting this error after the video has been initialized: 
`ERROR: DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.`

```
this.video = videojs('landing-yt-video', {
                sources: [{
                    type: 'video/youtube',
                    src: 'https://www.youtube.com/watch?v=mZsaaturR6E'
                }],
                youtube: {
                    iv_load_policy: 1
                },
                muted: true,
                autoplay: true,
                controls: false,
                preload: 'auto',
                loop: true,
                fluid: true,
                techOrder: ['youtube']
            }, function(){
                var _this = this;
                $('.bg-video-switch').off('click').remove();

                $('.bg-video-control').off('click');
                $('.bg-video-control').on('click', function() {
                    _this.paused() ? _this.play() : _this.pause();
                });
                this.muted(true);
            });
```

Any idea why this might be happening?

**Comment by Jule-** [comment]
Same thing here!
May be it is matter of collision between Youtube controls and VideoJS controls... It happens when you mouseout the player on controls hiding.

More about the error, it appends in `LoadProgressBar.update`:
```
VIDEOJS: ERROR: DOMException: Failed to execute 'removeChild' on 'Node': The node to be removed is not a child of this node.
    at LoadProgressBar.update ([.../]video.js@5.12.6/dist/video.js:1891:24)
    at Player.ret ([.../]video.js@5.12.6/dist/video.js:11118:23)
    at HTMLDivElement.ret ([.../]video.js@5.12.6/dist/video.js:11118:23)
    at HTMLDivElement.data.dispatcher ([.../]video.js@5.12.6/dist/video.js:11008:39)
    at Object.trigger ([.../]video.js@5.12.6/dist/video.js:11074:33)
    at Player.trigger ([.../]video.js@5.12.6/dist/video.js:748:20)
    at Player.(anonymous function) [as handleTechProgress_] ([.../]video.js@5.12.6/dist/video.js:6279:25)
    at constructor.ret ([.../]video.js@5.12.6/dist/video.js:11118:23)
    at HTMLDivElement.ret ([.../]video.js@5.12.6/dist/video.js:11118:23)
    at HTMLDivElement.data.dispatcher ([.../]video.js@5.12.6/dist/video.js:11008:39)
```

**Comment by biegl** [comment]
I'm experiencing the same problem on localhost. Surprisingly, when I run it on my production server, the error does not show up.

**Comment by clark-stevenson** [comment]
On the latest build I get a `RangeError` which isn't exactly the same as the error as above but very close. 

```
VIDEOJS: ERROR: RangeError: Invalid array length
    at LoadProgressBar.update (http://x/lib/videojs/video.js:4087:21)
    at Player.bound (http://x/lib/videojs/video.js:21135:15)
    at HTMLDivElement.bound (http://x/lib/videojs/video.js:21135:15)
    at HTMLDivElement.data.dispatcher (http://x/lib/videojs/video.js:20926:31)
    at Object.trigger (http://x/lib/videojs/video.js:21048:25)
    at Player.trigger (http://x/lib/videojs/video.js:1771:12)
    at Player.(anonymous function) [as handleTechProgress_] (http://x/lib/videojs/video.js:10885:243)
    at constructor.bound (http://x/lib/videojs/video.js:21135:15)
    at HTMLDivElement.bound (http://x/lib/videojs/video.js:21135:15)
    at HTMLDivElement.data.dispatcher (http://x/lib/videojs/video.js:20926:31)
```

Inside the else here. 

```
  // Old IE versions do not allow .apply() for console methods (they are
  // reported as objects rather than functions).
  if (!fn.apply) {
    fn(args);
  } else {
    fn[Array.isArray(args) ? 'apply' : 'call'](_window2['default'].console, args);
  }
```

**Comment by gkatsev** [comment]
Looks like https://github.com/videojs/videojs-youtube/pull/411 fixes this issue.

**Comment by clark-stevenson** [comment]
Confirmed, the problem is now gone. Thanks 👍
