### ISSUE TITLE
VIDEOJS: ERROR: The "youtube" tech is undefined. Skipped browser support check for that tech

### ISSUE THREAD

**Issue by akshaykatale99** [videojs/videojs-youtube#569]
VIDEOJS: ERROR: The "youtube" tech is undefined. Skipped browser support check for that tech

"video.js": "^7.8.4",
"videojs-youtube": "^2.0.8",

**Comment by OtavioBraga0** [comment]
I updated my versions to: 

"video.js": "^7.10.2",
"videojs-youtube": "^2.6.1",

And it worked for me

**Comment by rodrigo-arias** [comment]
It doesn't work for me with

"video.js": "^7.10.2",
"videojs-youtube": "^2.6.2",

I also tried version 2.6.1 with no luck.

**Comment by satishbluone** [comment]
I am also facing same error and I am using following versions with angular 10
"video.js": "^7.11.4"
"videojs-youtube": "^2.6.1",

Can you please show me any example to play the youtube video in angular 10?

**Comment by Famondir** [comment]
Hi I tried it with
"video.js": "^7.18.0"
"videojs-youtube": "^2.6.1"
and had no luck. My codepen throws the error mentioned in the thread title: https://codepen.io/Famondir/pen/rNYvrYz

On a Moodle page (where I want to use this) I get the error:
```
Youtube.min.js:1 
        
       Uncaught TypeError: Cannot read properties of undefined (reading 'browser')
    at Youtube.min.js:1:392
    at Youtube.min.js:1:307
    at Youtube.min.js:1:331
```

I import the scripts via cdn.

Can anyone help me out?

**Comment by ItamarSilverstein** [comment]
Any news regarding this error ?
I get this same error ("the youtube" tech is undefined) on:
"video.js": "^7.18.1",
"videojs-youtube": "^2.6.1"

how do you recommend on loading the libraries together ?
via <script> tags? lazy load them ?
or with import videojs from "video.js", and when and how to load the youtube script ?
Thanks!

**Comment by gkatsev** [comment]
> how do you recommend on loading the libraries together ?

you can load it either via `<script>` or via `import`/`require`. In either case, you'd want to include video.js first and then the youtube tech.
You'd also want to make sure that the youtube tech script has loaded before you initialize the player.

The [simple example](https://github.com/videojs/videojs-youtube/blob/master/examples/simple.html) should generally work, and works every time locally because both scripts load quickly, but there's a danger that video.js will try initializing the player automatically before the youtube tech is available, so, might be worth initializing it manually instead of using data-setup.

**Comment by ItamarSilverstein** [comment]
@gkatsev 
Thanks!
```
it worked as you said, manually by:
        1.
        loadYoutubeVideoJS(videojs);
        2.
        this.videoJsPlayer = videojs(this.videojsId, {
            techOrder: ["youtube"], "sources": [{ "type": "video/youtube", "src": "https://www.youtube.com/watch?v=xjS6SftYQaQ"}]
        });
```
are there any limitations that one will have using this plugin and not have in youtube embed ?

**Comment by gkatsev** [comment]
Hm... if you're using a bundler, I'd expect import to work. Though, the youtube tech is set up as a UMD module and video.js is set up as a hybrid package, so, it's possible at this point the youtube tech ends up loading a different version of video.js than your import.

This tech runs the standard youtube embed, so, no extra limitations beyond the ones imposed by youtube.

**Comment by hungtd97** [comment]
@gkatsev I'm using bundler with Webpack but import doesn't work. 
videojs-youtube uses a different instance of video.js as you said. Do you have any advice?

**Comment by gkatsev** [comment]
I'd expect it to work if you're using Video.js 7 (it doesn't really work with v8 right now).

If you can set up a minimal test example on codesandbox.io, I can take a look.

**Comment by hungtd97** [comment]
@gkatsev yeah, I downgrade to version 7 and it works great. Many thanks to you.
